config/routes.rb
FollowThru::Application.routes.draw do

  # Logged in
  authenticated :user do
    
    # Basic site layout!
    root :to => 'home#index'
    match "/about" => "home#about", :as => :home_about
	  match "/browse" => "home#browse_project", :as => :home_browse
	  match "/browse/:id" => "home#show_project", :as => :home_show
    match "/manage" => "home#manage_project", :as => :home_manage
    match "/all" => "home#index", :as => :home_all
    match "/new" => "home#create_project", :as => :home_new

    # For managing projects, base urls
    match "/project/new" => "project_control#new", :as => :project_new
    match "/project/list" => "project_control#list", :as => :project_list
    match "/project/view" => "project_control#view", :as => :project_view_base
    match "/project/edit" => "project_control#edit", :as => :project_edit_base
    match "/project/delete" => "project_control#delete", :as => :project_delete_base

    # Specific url patterns for editing items, etc.
    match "/project/view/:id" => "project_control#view", :as => :project_view
    match "/project/delete/:id" => "project_control#delete", :as => :project_delete
    match "/project/edit/:id" => "project_control#edit", :as => :project_edit

    # Dynamic ajax actions
    resources :pledges, :path => "ajax/pledges"
    resources :projects, :path => "ajax/projects"
    resources :pledge_types, :path => "ajax/pledge_types"
    resources :goals, :path => "ajax/goals"
  end

  # Not logged in? All you can see the homepage.
  root :to => "home#index"

  # Auth control
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/controllers/project_control_controller.rb
class ProjectControlController < ApplicationController
  def new
  end
  def list
  end
  def view
    @id = params[:id]
  end
  def delete
    @id = params[:id]
  end
  def edit
    @id = params[:id]
  end
end

app/helpers/project_control_helper.rb
module ProjectControlHelper
end

app/views/project_control/delete.html.erb
<img src="/images/home_4.jpg" />

<h1 class="introduction">Delete project</h1>

<script>
  window.DeleteProjectControllerData = {
    id : <%= @id %>
  };
</script>

<div ng-controller="DeleteProjectController">

  <div ng-show="valid && !done">
    <h2>Are you sure you want to delete that? No going back... </h2>
    <input type="button" ng-click="remove()" value="Yeah, really delete that"/>
  </div>

  <div ng-hide="valid">
    That doesn't seem to be a valid project.
  </div>

  <div ng-show="error">
    Looks like something went wrong! Sorry!
  </div>

  <div ng-show="done">
    Project destroyed.
  </div>

</div>

app/views/project_control/edit.html.erb
<img src="/images/home_4.jpg" />

<h1 class="introduction">Edit project</h1>

<script>
  window.EditProjectControllerData = {
    id : <%= @id %>
  };
</script>

<div ng-controller="EditProjectController">
  <div hg-show="valid">

    <h2>Tell us a bit about your project</h2>
    <div>
      Status: {{project.status}} <a ng-show="projectIsNew" ng-click="makeProjectLive()" href="#">Make this live</a>
    </div>
    <div>
      Name; <input type="text" ng-model="project.name"/>
    </div>
    <div>
      Image: <input type="text" ng-model="project.image"/>
    </div>
    <div>
      Desc: <textarea ng-model="project.desc"></textarea>
    </div>
    <div>
      Objective: <input type="text" ng-model="project.objective"/>
    </div>
    <div>
      Private: <input type="checkbox" ng-model="project.private"/>
    </div>
    <button>Update project</button>

    <div>
      <h3> Pledge Types </h3>

      <div style="vertical-align: top; border: 1px solid #efefef; padding: 20px; display: inline-block; width: 40%;">
        Current pledge types 

        <ul ng-show="pledgeTypesCount">
          <li ng-repeat="item in pledgeTypes">
            Name: {{item.name}}
            Desc: {{item.desc}}
            Image: {{item.image}}
            Minimum amount for pledge: {{ item.amount }} --
            <button ng-click="editPledgeType({{item.id}})">Edit</button>
            <button ng-click="deletePledgeType({{item.id}})">Delete</button>
          </li>
        </ul>

        <div ng-hide="pledgeTypesCount">
          No current pledge types
        </div>
      </div>

      <div style="vertical-align: top; border: 1px solid #efefef; padding: 20px; display: inline-block; width: 40%;">
        <div ng-show="pledgeTypeHasErrors">
          Errors saving record:
          <ul>
            <li ng-repeat="error in pledgeTypeErrors">
              {{ error.field }} - {{ error.error }}
            </li>
          </ul>
        </div>

        <div ng-show="pledgeTypeSuccess">
          Record added. <a href="#" ng-click="hidePledgeTypeSuccess()">hide</a>
        </div>

        <div ng-hide="pledgeTypeSuccess">
          Id: <input type="text" ng-model="pledgeType.id"/> <br/>
          Name: <input type="text" ng-model="pledgeType.name"/> <br/>
          Desc: <input type="text" ng-model="pledgeType.desc"/> <br/>
          Image: <input type="text" ng-model="pledgeType.image"/> <br/>
          Minimum amount for pledge: <input type="text" ng-model="pledgeType.amount"/> <br/>
          <button ng-click="addPledgeType()">Save</button>
          <button ng-click="resetPledgeType()">New record</button>
        </div>
      </div>

    </div>

    <div>
      <h3> Goals </h3>

      <div style="vertical-align: top; border: 1px solid #efefef; padding: 20px; display: inline-block; width: 40%;">
        Current goals:

        <ul ng-show="goalsCount">
          <li ng-repeat="item in goals">
            Amount: {{ item.total }} --
            Pledge type: {{ item.pledge_type_id }} --
            Pledge instances: {{ item.instances }}
            <button ng-click="editGoal({{item.id}})">Edit</button>
            <button ng-click="deleteGoal({{item.id}})">Delete</button>
          </li>
        </ul>

        <div ng-hide="goalsCount">
          No current goals
        </div>
      </div>

      <div style="vertical-align: top; border: 1px solid #efefef; padding: 20px; display: inline-block; width: 40%;">
        <div ng-show="goalHasErrors">
          Errors saving record:
          <ul>
            <li ng-repeat="error in goalErrors">
              {{ error.field }} - {{ error.error }}
            </li>
          </ul>
        </div>

        <div ng-show="goalSuccess">
          Record added. <a href="#" ng-click="hideGoalSuccess()">hide</a>
        </div>

        <div ng-hide="goalSuccess">
          Id: <input type="text" ng-model="goal.id"/> <br/>
          Minimum amount to succeed: <input type="text" ng-model="goal.total"/> <br/>
          Pledge type: 
          <select ng-model="goal.pledge_type_id">
            <option ng-repeat="item in pledgeTypes" value="{{item.id}}">{{item.name}}</option>
          </select> <br/>
          Number of instances of that pledge type (0 for no pledge type): <input type="text" ng-model="goal.instances"/> <br/>
          <button ng-click="addGoal()">Save</button>
          <button ng-click="resetGoal()">New record</button>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/project_control/list.html.erb
<img src="/images/home_2.jpg" />

<h1 class="introduction">Manage my projects</h1>

<%# Rails doesn't handle urls in the assets pipeline %>
<script>
  window.ListProjectControllerData = {
    'baseEditUrl' : '<%= project_edit_base_url %>',
    'baseViewUrl' : '<%= project_view_base_url %>',
    'baseDeleteUrl' : '<%= project_delete_base_url %>',
  };
</script>

<div ng-controller="ListProjectController">

  <h2>You have <strong>{{ projects.new.count }}</strong> new projects</h2>

	<div class="container-inner" ng-hide="projects.new.count">
    You don't have any active projects.
  </div>

	<div class="container-inner" ng-show="projects.new.count">
		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th>Status</th>
					<th>Name</th>
					<th>Desc</th>
					<th>Objective</th>
					<th>Private</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="project in projects.new.items">
					<td><img src="http://placekitten.com/50/50/" /><!-- {{project.id}} {{project.image}} --></td>
					<td>{{project.status}}</td>
					<td><a href="{{project.viewUrl}}">{{project.name}}</a></td>
					<td>{{project.desc}}</td>
					<td>{{project.objective}}</td>
					<td>{{project.private}}</td>
					<td><i class="icon icon-eye-open"></i> <a href="{{project.viewUrl}}">Show</a></td>
					<td><i class="icon icon-edit"></i> <a href="{{project.editUrl}}">Edit</a></td>
					<td><i class="icon icon-trash"></i> <a href="{{project.deleteUrl}}">Delete</a></td>
				</tr>
			</tbody>
		</table>
	</div>

  <h2>You have <strong>{{ projects.active.count }}</strong> running projects</h2>

	<div class="container-inner" ng-hide="projects.active.count">
    You don't have any active projects.
  </div>

	<div class="container-inner" ng-show="projects.active.count">
		<table class="table">
			<thead>
				<tr>
					<th>Image</th>
					<th>Status</th>
					<th>Name</th>
					<th>Desc</th>
					<th>Objective</th>
					<th>Private</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="project in projects.active.items">
					<td>{{project.id}} {{project.image}}</td>
					<td>{{project.status}}</td>
					<td><a href="{{project.viewUrl}}">{{project.name}}</a></td>
					<td>{{project.desc}}</td>
					<td>{{project.objective}}</td>
					<td>{{project.private}}</td>
					<td><i class="icon icon-eye-open"></i> <a href="{{project.viewUrl}}">Show</a></td>
					<td><i class="icon icon-trash"></i> <a href="{{project.deleteUrl}}">Delete</a></td>
				</tr>
			</tbody>
		</table>
	</div>

  <h2>Successful projects</h2>

	<div class="container-inner" ng-hide="projects.success.count">
    You don't have any successful projects yet.
  </div>

	<div class="container-inner" ng-show="projects.success.count">
		<table class="table">
			<thead>
				<tr>
					<th>Image</th>
					<th>Name</th>
					<th>Desc</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="project in projects.success.items">
					<td>{{project.id}} {{project.image}}</td>
					<td>{{project.name}}</td>
					<td>{{project.desc}}</td>
					<td><i class="icon-book"></i> Track pledges</td>
					<td><i class="icon-refresh"></i> Recycle project</small></td>
					<td><i class="icon-trash"></i> Delete</td>
				</tr>
			</tbody>
		</table>
	</div>

  <h2>Shelved projects</h2>

	<div class="container-inner" ng-hide="projects.failed.count">
    You don't have any shelved projects yet.
  </div>

	<div class="container-inner" ng-show="projects.failed.count">
		<table class="table">
			<thead>
				<tr>
					<th>Image</th>
					<th>Name</th>
					<th>Desc</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="project in projects.failed.items">
					<td>{{project.id}} {{project.image}}</td>
					<td>{{project.name}}</td>
					<td>{{project.desc}}</td>
					<td><i class="icon-eye-open"></i> View</td>
					<td><i class="icon-refresh"></i> Recycle project</small></td>
					<td><i class="icon-trash"></i> Delete</td>
				</tr>
			</tbody>
		</table>
	</div>

</div>

app/views/project_control/new.html.erb
<img src="/images/home_4.jpg" />

<h1 class="introduction">Create a new project</h1>

<h2>Tell us a bit about your project to get started</h2>

<form class="form-horizontal">
<div ng-controller="CreateProjectController">
  <div ng-show="hasErrors">
    Errors:
    <ul>
      <li ng-repeat="error in errors">
        <div> {{error.field}} -- {{error.error}} </div>
      </li>
    </ul>
  </div>
  <div ng-show="success">
    <p class="lead">Success!</p>
	<p>You're off to a good start. <a href="/project/list/">Your project has been created.</a></p>
	<p>From here, you'll want to add more detail before publishing.</a>
  </div>

  <div ng-hide="success">
  
  	<div class="control-group">
		<label for="project_name" class="control-label">Project name</label>
		<div class="controls">
			<input type="text" ng-model="project.name" name="project_name" />
		</div>
	</div>
	
	<div class="control-group">
		<label for="desc" class="control-label">Short description</label>
		<div class="controls">
			<textarea ng-model="project.desc" rows="4"></textarea>
		</div>
	</div>
	
	<div class="control-group">
		<label for="image" class="control-label">Project avatar</label>
		<div class="controls">
			<input type="file" ng-model="project.image" name="image" />		
		</div>
	</div>

	<div class="control-group">
		<label for="project_type" class="control-label">What is your objective?</label>
		<div class="controls">
			<select name="project_type" ng-model="project.objective">
				<option value="Shopping">I am getting something and want to see if others would like some too.</option>
				<option value="Project">I will arrange something if enough people are interested.</option>
				<option value="Gift">I am organising a gift and wish to let people contribute.</option>
				<option value="Idea">I have an idea and would like people support me.</option>
			</select>
		</div>
	</div>
	
	<div class="control-group">
		<div class="controls">
			<label class="checkbox">
				<input type="checkbox" value="" checked ng-model="public">
				This project is open to everyone.
				<p><small>Unticking this box means only people who have the link will be able to find your project.</small></p>
			</label>
		</div>
	</div>

	<div class="control-group">
		<div class="controls">
    		<button class="btn btn-success" ng-click="create()" type="button">Create this project</button>
		</div>
	</div>

  </div>


</div>
</form>

app/views/project_control/view.html.erb
<script>
  window.ViewProjectControllerData = {
    'id' : <%= @id %>
  };
</script>

<div ng-controller="ViewProjectController">
  <div ng-hide="valid">
    This doesn't seem to be a valid project.
  </div>

	<div ng-show="valid">

		<h1>{{project.name}}</h1>
		
		<p><small><%= current_user.name %> || {{project.objective}}</small></p>

		<div class="container-inner">		
		<div class="col3 col3-doubleleft">
		
			<img src="http://placekitten.com/720/300" class="project-image" />

			<p class="lead-first">{{project.desc}}</p>
			
			<p>PROJECT MENU OPTIONS, PLEDGING, ETC. GOES HERE</p>
			
			<h2>Support this project!</h2>
			
			  <div ng-hide="pledgeTypeCount">
				No pledge types for this project.
			  </div>
		
        <style>
          .pledge-type {
            border: 1px solid #333;
            background: #efefef;
            border-radius: 8px;
            padding: 4px;
            margin: 10px;
            width: 300px;
            display: inline-block;
          }
          .pledge-type img {
            float: left;
            margin: 3px;
          }
          .pledge-type .info {
            margin-left: 96px;
            margin-top: 8px;
          }
        </style>

			  <div ng-show="pledgeTypeCount" class="pledge-type-container"> 
          <div ng-repeat="item in pledgeTypes" class="pledge-type">
            <img src="http://placekitten.com/82/50"> 
            <div class="info">
              <b>${{item.amount}}0</b> - {{item.name}} <br/>
              {{item.desc}}
            </div>
          </div>
			  </div>
				
			  <div ng-hide="myPledgeCount">
				You have not pledged to this project
			  </div>

			  <!--<div ng-show="myPledgeCount"> 
				Your pledges:
				<div ng-repeat="item in myPledges">
				  ${{item.amount}} - {{item.pledge_type_id}}
				</div>
			  </div>
		
			  <div ng-show="pledgeFailed">
				<ul>
				  <li ng-repeat="item in pledgeErrors">
					{{ item.field }} {{ item.error }}
				  </li>
				</ul>
			  </div> -->
			  
			  <h3>Add a pledge</h3>
			  
			  <form class="form-horizontal">
			  
			  	<div class="control-group">
					<label for="amt" class="control-label">Pledge amount</label>
					<div class="controls">
						<input type="text" name="amt" ng-model="pledge.amount"/>
					</div>
				</div>

			  	<div class="control-group">
					<label for="pldgtp" class="control-label">Pledge amount</label>
					<div class="controls">
						<select ng-model="pledge.pledge_type_id" name="pldgtp">
							<option ng-repeat="item in pledgeTypes" value="{{item.id}}">{{item.name}}</option>
						</select>
					</div>
				</div>

			  	<div class="control-group">
					<div class="controls">
						<button ng-click="addPledge()" class="btn btn-success">Pledge to this project</button>
					</div>
				</div>
				
			  </form>

			<!-- <img src="{{project.image}}" /> -->
			
		</div>
		
		<div class="col3 col3-right breakout-box">
		
			<div class="progress progress-success progress-striped">
			  <div class="bar" style="width: 40%"></div>
			</div>
			
			<p><em>2 pledges out of 5 needed!</em></p>
		
			<p>Status: {{project.status}}</p>
			
			<p>This is a PRIVATE/PUBLIC project. {{project.private}}</p>

      <div>
        Goals:
        <ul>
          <li ng-repeat="item in goals">
            ${{item.amount}}, {{item.pledge_type_id}} x {{item.instances}}
          </li>
      </div>

		</div>

  </div>
  

	</div><!-- end of show valid -->

</div>