config/routes.rb
FollowThru::Application.routes.draw do

  # Logged in
  authenticated :user do
    
    # Basic site layout!
    root :to => 'home#index'
    match "/about" => "home#about", :as => :home_about
	  match "/browse" => "home#browse_project", :as => :home_browse
	  match "/browse/:id" => "home#show_project", :as => :home_show
    match "/manage" => "home#manage_project", :as => :home_manage
    match "/all" => "home#index", :as => :home_all
    match "/new" => "home#create_project", :as => :home_new

    # For managing projects, base urls
    match "/project/new" => "project_control#new", :as => :project_new
    match "/project/list" => "project_control#list", :as => :project_list
    match "/project/view" => "project_control#view", :as => :project_view_base
    match "/project/edit" => "project_control#edit", :as => :project_edit_base
    match "/project/delete" => "project_control#delete", :as => :project_delete_base

    # Specific url patterns for editing items, etc.
    match "/project/view/:id" => "project_control#view", :as => :project_view
    match "/project/delete/:id" => "project_control#delete", :as => :project_delete
    match "/project/edit/:id" => "project_control#edit", :as => :project_edit

    # Dynamic ajax actions
    resources :pledges, :path => "ajax/pledges"
    resources :projects, :path => "ajax/projects"
    resources :pledge_types, :path => "ajax/pledge_types"
    resources :goals, :path => "ajax/goals"
  end

  # Not logged in? All you can see the homepage.
  root :to => "home#index"

  # Auth control
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.all
  end

  def browse_project
    @projects = Project.where("status == ?", Project::ACTIVE)
  end

  # Different to the projects_controller because this one is not limited to owner only.
  def show_project
    @project = Project.find(params[:id])
    @id = @project.id
    respond_to do |format|
      format.html { render 'project_control/view' }
      format.json { render json: @project }
    end
  end

  def create_project
    redirect_to project_new_path
  end

  def manage_project
    redirect_to project_list_path
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<img src="/images/home_3.jpg" />

<h1 class="introduction">About Followthru</h1>

<p class="lead"><strong>Followthru</strong> is our in-house kickstarter system.</p>

<p>You've heard of crowdfunding sites like <a href="http://www.kickstarter.com/">Kickstarter</a>, <a href="http://www.indiegogo.com/">Indiegogo</a> and <a href="http://www.pozible.com/">Pozible</a> - well, this is the same deal.</p>

<p>Created by Doug Linder and Sandy Lim for the August 2012 iiNet Deliverance Day.</p>

<h2>How does this work</h2>

<div class="container-inner">

	<div class="col3 col3-left">
		<p>When organising a group activity, like lunch orders, birthday collections, farewell chip-ins and collaborations, you <%= link_to 'create a project', home_new_path %>, set any necessary goals (eg. more than 5 people want curry today), then put out the call to your workmates.</p>
	</div>
	
	<div class="col3 col3-mid">
		<p>If your project reaches its goal, you'll find it filed under your <%= link_to 'successful projects', home_manage_path %>, where you can track everyone who's pledged and paid, and know whether you physically have enough to follow through with your plan.</p>
	</div>

	<div class="col3 col3-right">
		<p>If you don't get all the pledges you need, we'll <%= link_to 'shelve your project', home_manage_path %> in case the future you wants to try again. Shelved projects retain all the details, goals and win conditions that you configured, but you'll need to ask your supporters to pledge once more.</p>
	</div>

</div>

app/views/home/browse_project.html.erb
<img src="/images/home_5.jpg" />

<h1 class="introduction">Browse all public projects</h1>

<div>
  <h2>There are <strong ng-model="projectCount">{{ projectCount }}</strong> public projects</h2>

	<div class="container-inner">

		<table class="table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Description</th>
					<th>Link</th>
				</tr>
			</thead>
			
			<tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><%= project.name %></td>
            <td><%= project.desc %></td>
            <td><%= link_to "Link", home_show_path(:id => project.id) %></td>
          </tr>
        <% end %>
			</tbody>
		
		</table>

	</div>

</div>

app/views/home/create_project.html.erb
this file is no longer used

app/views/home/index.html.erb
<img src="/images/home_1.jpg" />

<h1 class="introduction">Food orders, coffee runs, birthday collections and more - made easier with Followthru.</h1>

<div class="container-inner">

	<div class="col3 col3-doubleleft">
	
		<h2>Most popular projects</h2>
		
		<ul class="project-quilt">
			<li>
				<img src="http://placekitten.com/202/100">
				<p><a href="">Cat herding... and breakfast!</a></p>
				<p>A team-building activity that starts at the Cat Haven and ends at a Chinese restaurant.</p>
				<div class="go-pledge">
					<p><small>5 pledges out of 6 needed.</small></p>
					<button type="button" class="btn btn-success">Support this project</button>
				</div>
			</li>
			<li>
				<img src="http://placekitten.com/202/100">
				<p><a href="">Kitten Burgers</a></p>
				<p>Let's dress up kittens in burger costumes and take photos all day. It's crazy burgers!</p>
				<div class="go-pledge">
					<p><small>3 pledges so far.</small></p>
					<button type="button" class="btn btn-success">Support this project</button>
				</div>
			</li>
			<li>
				<img src="http://placekitten.com/202/100">
				<p><a href="">Samurai Pizza Cats</a></p>
				<p>I feel like getting pizza today. Anyone else want some?</p>
				<div class="go-pledge">
					<p><small>32 pledges so far.</small></p>
					<button type="button" class="btn btn-success">Support this project</button>
				</div>
			</li>
			<li>
				<img src="http://placekitten.com/202/100">
				<p><a href="">A generic project</a></p>
				<p>Just looking to see who's keen on helping me with a generic project. Sorry, no rewards.</p>
				<div class="go-pledge">
					<p><small>0 pledges out of 6 needed.</small></p>
					<button type="button" class="btn btn-success">Support this project</button>
				</div>
			</li>
			<li>
				<img src="http://placekitten.com/202/100">
				<p><a href="">Deliverance day 3</a></p>
				<p>We're doing this again. Who's interested?</p>
				<div class="go-pledge">
					<p><small>300 pledges so far.</small></p>
					<button type="button" class="btn btn-success">Support this project</button>
				</div>
			</li>
			<li>
				<img src="http://placekitten.com/202/100">
				<p><a href="">Bye bye, kitty</a></p>
				<p>Kitty is leaving tomorrow. Let's get her a present. Shh, keep this a secret.</p>
				<div class="go-pledge">
					<p><small>$30 out of $400 needed.</small></p>
					<button type="button" class="btn btn-success">Support this project</button>
				</div>
			</li>
		</ul>
		
		<p><%= link_to 'Check out more projects...', home_browse_path %>
		
	</div>
	
	<div class="col3 col3-right">

		<h3>Organise group projects with ease.</h3>
		
		<p><strong>Followthru</strong> is a crowdsourcing, crowdfunding system that helps you get the resources and support you need to follow through with your idea.</p>
		
		<p><%= link_to 'Create a project', home_new_path %>, set any necessary goals, then put out the call to your workmates. Once your project meets its target, you can track all pledges and payments, and generate friendly reminders as needed.</p>
		
		<h3>For supporters:</h3>
		
		<ul>
			<li><a href="">I'd like to get in on someone's shopping order</a></li>
			<li><a href="">I want to participate in a special event</a></li>
			<li><a href="">I wish to contribute to a gift</a></li>
			<li><a href="">I want to offer my services to a group project</a></li>
		</ul>

		<h3>Got an idea for a project?</h3>
		
		<ul>
			<li><%= link_to 'Create your Followthru project now', home_new_path %></li>
		</ul>
		
		<h3>Browse for projects by location</h3>
		
		<ul>
			<li><a href="">Subiaco, WA, AU</a></li>
			<li><a href="">Sydney, NSW, AU</a></li>
			<li><a href="">Auckland, NZ</a></li>
			<li><a href="">Melbourne, VIC, AU</a></li>
			<li><a href="">Cape Town, South Africa</a></li>
		</ul>

		<h3>Most popular users</h3>
		
		<ul>
		<% @users.each do |user| %>
			<li>User: <%=link_to user.name, user %></li>
		<% end %>
		</ul>
	
	</div>

</div>

app/views/home/manage_project.html.erb
<img src="/images/home_2.jpg" />

<h1 class="introduction">Manage my projects</h1>

<p>You have <strong>X NUMBER</strong> projects open:</p>

<table class="projects">
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <tr>
    <td>[IMG]</td>
    <td>dummy project name</td>
    <td>Bacon ipsum dolor sit amet meatball brisket strip steak pork loin chicken salami. Ground round jerky brisket, ball tip tri-tip t-bone short loin hamburger frankfurter pork chop turducken salami sirloin swine chuck.</td>
    <td>Show</td>
    <td>Edit</td>
    <td>Delete forever</td>
  </tr>
  <tr>
    <td>[IMG]</td>
    <td>dummy project name</td>
    <td>Bacon ipsum dolor sit amet meatball brisket strip steak pork loin chicken salami. Ground round jerky brisket, ball tip tri-tip t-bone short loin hamburger frankfurter pork chop turducken salami sirloin swine chuck.</td>
    <td>Show</td>
    <td>Edit</td>
    <td>Delete forever</td>
  </tr>
  <tr>
    <td>[IMG]</td>
    <td>dummy project name</td>
    <td>Bacon ipsum dolor sit amet meatball brisket strip steak pork loin chicken salami. Ground round jerky brisket, ball tip tri-tip t-bone short loin hamburger frankfurter pork chop turducken salami sirloin swine chuck.</td>
    <td>Show</td>
    <td>Edit</td>
    <td>Delete forever</td>
  </tr>

</table>

<h2>Successful projects</h2>

<p>PROJECTS THAT MET THE TARGET</p>

<h2>Shelved projects</h2>

<p>PROJECTS THAT DIDN'T MEET THE TARGET</p>