config/routes.rb
FollowThru::Application.routes.draw do

  # Logged in
  authenticated :user do
    
    # Basic site layout!
    root :to => 'home#index'
    match "/about" => "home#about", :as => :home_about
	  match "/browse" => "home#browse_project", :as => :home_browse
	  match "/browse/:id" => "home#show_project", :as => :home_show
    match "/manage" => "home#manage_project", :as => :home_manage
    match "/all" => "home#index", :as => :home_all
    match "/new" => "home#create_project", :as => :home_new

    # For managing projects, base urls
    match "/project/new" => "project_control#new", :as => :project_new
    match "/project/list" => "project_control#list", :as => :project_list
    match "/project/view" => "project_control#view", :as => :project_view_base
    match "/project/edit" => "project_control#edit", :as => :project_edit_base
    match "/project/delete" => "project_control#delete", :as => :project_delete_base

    # Specific url patterns for editing items, etc.
    match "/project/view/:id" => "project_control#view", :as => :project_view
    match "/project/delete/:id" => "project_control#delete", :as => :project_delete
    match "/project/edit/:id" => "project_control#edit", :as => :project_edit

    # Dynamic ajax actions
    resources :pledges, :path => "ajax/pledges"
    resources :projects, :path => "ajax/projects"
    resources :pledge_types, :path => "ajax/pledge_types"
    resources :goals, :path => "ajax/goals"
  end

  # Not logged in? All you can see the homepage.
  root :to => "home#index"

  # Auth control
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/controllers/pledge_types_controller.rb
class PledgeTypesController < ApplicationController
  # GET /pledge_types
  # GET /pledge_types.json
  def index
    ud = UserDataFactory.new.get current_user, Userdatum
    if params.has_key?(:project_id) 
      @pledge_types = PledgeType.where("userdatum_id = ? AND project_id = ?", ud.id, params[:project_id])
    else
      @pledge_types = PledgeType.where("userdatum_id = ?", ud.id)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pledge_types }
    end
  end

  # GET /pledge_types/1
  # GET /pledge_types/1.json
  def show
    ud = UserDataFactory.new.get current_user, Userdatum
    @pledge_type = PledgeType.where("userdatum_id = ? AND id = ?", ud.id, params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pledge_type }
    end
  end

  # GET /pledge_types/new
  # GET /pledge_types/new.json
  def new
    @pledge_type = PledgeType.new
    @pledge_type.userdatum = UserDataFactory.new.get current_user, Userdatum

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pledge_type }
    end
  end

  # GET /pledge_types/1/edit
  def edit
    ud = UserDataFactory.new.get current_user, Userdatum
    @pledge_type = PledgeType.where("userdatum_id = ? AND id = ?", ud.id, params[:id])
  end

  # POST /pledge_types
  # POST /pledge_types.json
  def create
    @pledge_type = PledgeType.new(params[:pledge_type])
    @pledge_type.userdatum = UserDataFactory.new.get current_user, Userdatum

    respond_to do |format|
      if @pledge_type.save
        format.html { redirect_to @pledge_type, notice: 'Pledge type was successfully created.' }
        format.json { render json: @pledge_type, status: :created, location: @pledge_type }
      else
        format.html { render action: "new" }
        format.json { render json: @pledge_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pledge_types/1
  # PUT /pledge_types/1.json
  def update
    ud = UserDataFactory.new.get current_user, Userdatum
    @pledge_type = PledgeType.where("userdatum_id = ? AND id = ?", ud.id, params[:id])

    respond_to do |format|
      if @pledge_type.update_attributes(params[:pledge_type])
        format.html { redirect_to @pledge_type, notice: 'Pledge type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pledge_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pledge_types/1
  # DELETE /pledge_types/1.json
  def destroy
    ud = UserDataFactory.new.get current_user, Userdatum
    @pledge_type = PledgeType.where("userdatum_id = ? AND id = ?", ud.id, params[:id])
    @pledge_type.destroy

    respond_to do |format|
      format.html { redirect_to pledge_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pledge_types_helper.rb
module PledgeTypesHelper
end

app/views/pledge_types/_form.html.erb
<%= form_for(@pledge_type) do |f| %>
  <% if @pledge_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pledge_type.errors.count, "error") %> prohibited this pledge_type from being saved:</h2>

      <ul>
      <% @pledge_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pledge_types/edit.html.erb
<h1>Editing pledge_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @pledge_type %> |
<%= link_to 'Back', pledge_types_path %>

app/views/pledge_types/index.html.erb
<h1>Listing pledge_types</h1>

<table>
  <tr>
    <th>Project</th>
    <th>Name</th>
    <th>Desc</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pledge_types.each do |pledge_type| %>
  <tr>
    <td><%= pledge_type.project_id %></td>
    <td><%= pledge_type.name %></td>
    <td><%= pledge_type.desc %></td>
    <td><%= pledge_type.image %></td>
    <td><%= link_to 'Show', pledge_type %></td>
    <td><%= link_to 'Edit', edit_pledge_type_path(pledge_type) %></td>
    <td><%= link_to 'Destroy', pledge_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pledge type', new_pledge_type_path %>

app/views/pledge_types/new.html.erb
<h1>New pledge_type</h1>

<%= render 'form' %>

<%= link_to 'Back', pledge_types_path %>

app/views/pledge_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @pledge_type.project_id %>
</p>

<p>
  <b>Name:</b>
  <%= @pledge_type.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @pledge_type.desc %>
</p>

<p>
  <b>Image:</b>
  <%= @pledge_type.image %>
</p>


<%= link_to 'Edit', edit_pledge_type_path(@pledge_type) %> |
<%= link_to 'Back', pledge_types_path %>