config/routes.rb
FollowThru::Application.routes.draw do

  # Logged in
  authenticated :user do
    
    # Basic site layout!
    root :to => 'home#index'
    match "/about" => "home#about", :as => :home_about
	  match "/browse" => "home#browse_project", :as => :home_browse
	  match "/browse/:id" => "home#show_project", :as => :home_show
    match "/manage" => "home#manage_project", :as => :home_manage
    match "/all" => "home#index", :as => :home_all
    match "/new" => "home#create_project", :as => :home_new

    # For managing projects, base urls
    match "/project/new" => "project_control#new", :as => :project_new
    match "/project/list" => "project_control#list", :as => :project_list
    match "/project/view" => "project_control#view", :as => :project_view_base
    match "/project/edit" => "project_control#edit", :as => :project_edit_base
    match "/project/delete" => "project_control#delete", :as => :project_delete_base

    # Specific url patterns for editing items, etc.
    match "/project/view/:id" => "project_control#view", :as => :project_view
    match "/project/delete/:id" => "project_control#delete", :as => :project_delete
    match "/project/edit/:id" => "project_control#edit", :as => :project_edit

    # Dynamic ajax actions
    resources :pledges, :path => "ajax/pledges"
    resources :projects, :path => "ajax/projects"
    resources :pledge_types, :path => "ajax/pledge_types"
    resources :goals, :path => "ajax/goals"
  end

  # Not logged in? All you can see the homepage.
  root :to => "home#index"

  # Auth control
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/views/layouts/_footer.html.erb
<p><small>This is a footer with some tiny text in it. Wee! :)</small></p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<img src="/images/logo.png" />
<%= link_to "Followthru", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
	<li>
    <%= link_to 'Browse Projects', home_browse_path %>
    </li>
	<li>
    <%= link_to 'Create New Project', home_new_path %>
    </li>
	<li>
    <%= link_to 'Manage My Projects', home_manage_path %>
    </li>
    <li>
    <%= link_to 'My Account', edit_user_registration_path %>
    </li>
  	<li>
	<%= link_to 'About Followthru', home_about_path %>
	</li>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html ng-app="App">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= content_for?(:title) ? yield(:title) : "Followthru" %></title>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">

              <%= render 'layouts/messages' %>
              <%= yield %>	

        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
	<footer>
		<div class="container">
			<%= render 'layouts/footer' %>
		</div>
	</footer>
  </body>
</html>